const response = [
  {
    Id: '4016123',
    IsSeance: true,
    DisplayTempoLink: false,
    Debut: '2024-03-04T13:00:00',
    Fin: '2024-03-04T16:15:00',
    Planification:
      'Projet FabLab (Cours)\r\n<br />\r\nADJEDJ Ilann <br />\r\nNext-U Café - Open Space\r\n (NEXT-U - Campus de Lyon) \r\n',
    AssignmentColor: null,
    BorderColor: '#FF4000',
    Type: 'Cours',
    Description:
      'Projet FabLab (Cours)\r\n<br />\r\nADJEDJ Ilann <br />\r\nNext-U Café - Open Space\r\n (NEXT-U - Campus de Lyon) \r\n\r\n',
    CommentaireExterne: '<p>SEMAINE DE REGROUPEMENT<br />\nLancement du projet Fablab</p>',
  },
  {
    Id: '4016141',
    IsSeance: true,
    DisplayTempoLink: false,
    Debut: '2024-03-05T08:45:00',
    Fin: '2024-03-05T12:00:00',
    Planification:
      'Projet FabLab (Cours)\r\n<br />\r\nADJEDJ Ilann <br />\r\nNext-U Café - Open Space\r\n (NEXT-U - Campus de Lyon) \r\n',
    AssignmentColor: null,
    BorderColor: '#FF4000',
    Type: 'Cours',
    Description:
      'Projet FabLab (Cours)\r\n<br />\r\nADJEDJ Ilann <br />\r\nNext-U Café - Open Space\r\n (NEXT-U - Campus de Lyon) \r\n\r\n',
    CommentaireExterne: '<p>SEMAINE DE REGROUPEMENT<br />\nCoaching du projet Fablab</p>',
  },
  {
    Id: '4016165',
    IsSeance: true,
    DisplayTempoLink: false,
    Debut: '2024-03-05T16:00:00',
    Fin: '2024-03-05T18:00:00',
    Planification: 'Rencontre Expert (Cours)\r\n<br />\r\n<br />\r\n',
    AssignmentColor: null,
    BorderColor: '#FF4000',
    Type: 'Cours',
    Description: 'Rencontre Expert (Cours)\r\n<br />\r\n<br />\r\n\r\n',
    CommentaireExterne: '<p>Rencontre expert Leobotics</p>',
  },
  {
    Id: '4016182',
    IsSeance: true,
    DisplayTempoLink: false,
    Debut: '2024-03-06T08:45:00',
    Fin: '2024-03-06T12:00:00',
    Planification: 'Projet FabLab (EN LIGNE)\r\n<br />\r\nREINHARD Tatiana <br />\r\n',
    AssignmentColor: '#E8F5E9',
    BorderColor: '#FF4000',
    Type: 'Cours',
    Description: 'Projet FabLab (EN LIGNE)\r\n<br />\r\nREINHARD Tatiana <br />\r\n\r\n',
    CommentaireExterne:
      '<p>SEMAINE DE REGROUPEMENT<br />\nCoaching du projet Fablab <u><strong>en visio</strong></u></p>\n\n<p><strong>Campus Lyon - Participer &agrave; la r&eacute;union Zoom </strong>: https://us02web.zoom.us/j/7328722618?pwd=Z3NURHVSZVJhWisycjlWRE1SN3hyZz09<br />\nID de r&eacute;union&nbsp;: 732 872 2618<br />\nCode secret&nbsp;: 300839</p>',
  },
  {
    Id: '4016219',
    IsSeance: true,
    DisplayTempoLink: false,
    Debut: '2024-03-06T13:00:00',
    Fin: '2024-03-06T16:15:00',
    Planification: 'Projet FabLab (Autonomie)\r\n<br />\r\n<br />\r\n',
    AssignmentColor: null,
    BorderColor: null,
    Type: 'Cours',
    Description: 'Projet FabLab (Autonomie)\r\n<br />\r\n<br />\r\n\r\n',
    CommentaireExterne: '',
  },
  {
    Id: '4016238',
    IsSeance: true,
    DisplayTempoLink: false,
    Debut: '2024-03-07T08:45:00',
    Fin: '2024-03-07T12:00:00',
    Planification:
      'Projet FabLab (Cours)\r\n<br />\r\nADJEDJ Ilann <br />\r\nNext-U Café - Open Space\r\n (NEXT-U - Campus de Lyon) \r\n',
    AssignmentColor: null,
    BorderColor: '#FF4000',
    Type: 'Cours',
    Description:
      'Projet FabLab (Cours)\r\n<br />\r\nADJEDJ Ilann <br />\r\nNext-U Café - Open Space\r\n (NEXT-U - Campus de Lyon) \r\n\r\n',
    CommentaireExterne: '<p>SEMAINE DE REGROUPEMENT<br />\nCoaching du projet Fablab</p>',
  },
  {
    Id: '4016262',
    IsSeance: true,
    DisplayTempoLink: false,
    Debut: '2024-03-08T08:45:00',
    Fin: '2024-03-08T12:00:00',
    Planification:
      'Projet FabLab (Cours)\r\n<br />\r\nADJEDJ Ilann <br />\r\nNext-U Café - Open Space\r\n (NEXT-U - Campus de Lyon) \r\n',
    AssignmentColor: null,
    BorderColor: '#FF4000',
    Type: 'Cours',
    Description:
      'Projet FabLab (Cours)\r\n<br />\r\nADJEDJ Ilann <br />\r\nNext-U Café - Open Space\r\n (NEXT-U - Campus de Lyon) \r\n\r\n',
    CommentaireExterne: '<p>SEMAINE DE REGROUPEMENT<br />\nCoaching du projet Fablab</p>',
  },
  {
    Id: '4016283',
    IsSeance: true,
    DisplayTempoLink: false,
    Debut: '2024-03-08T13:00:00',
    Fin: '2024-03-08T15:00:00',
    Planification:
      'Projet FabLab (Evaluation)\r\n<br />\r\nADJEDJ Ilann <br />\r\nNext-U Café - Open Space\r\n (NEXT-U - Campus de Lyon) \r\n',
    AssignmentColor: null,
    BorderColor: '#FF4000',
    Type: 'Cours',
    Description:
      'Projet FabLab (Evaluation)\r\n<br />\r\nADJEDJ Ilann <br />\r\nNext-U Café - Open Space\r\n (NEXT-U - Campus de Lyon) \r\n\r\n',
    CommentaireExterne: '<p>SEMAINE DE REGROUPEMENT<br />\nSoutenances du projet Fablab</p>',
  },
  {
    Id: '4016302',
    IsSeance: true,
    DisplayTempoLink: false,
    Debut: '2024-03-07T13:00:00',
    Fin: '2024-03-07T16:15:00',
    Planification: 'Projet FabLab (Autonomie)\r\n<br />\r\n<br />\r\n',
    AssignmentColor: null,
    BorderColor: null,
    Type: 'Cours',
    Description: 'Projet FabLab (Autonomie)\r\n<br />\r\n<br />\r\n\r\n',
    CommentaireExterne: '',
  },
  {
    Id: '4016159',
    IsSeance: null,
    DisplayTempoLink: null,
    Debut: '2024-03-05T13:00:00',
    Fin: '2024-03-05T13:30:00',
    Planification: 'Présentation des Mastères WEBTECH Institute\r\nNext-U Café - Open Space\r\n',
    AssignmentColor: null,
    BorderColor: null,
    Type: null,
    Description: null,
    CommentaireExterne: '',
  },
  {
    Id: '4016256',
    IsSeance: null,
    DisplayTempoLink: null,
    Debut: '2024-03-05T13:30:00',
    Fin: '2024-03-05T16:00:00',
    Planification: 'Entretiens de suivi individuels\r\nNext-U Café - Open Space\r\n',
    AssignmentColor: null,
    BorderColor: null,
    Type: null,
    Description: null,
    CommentaireExterne:
      '<p>ALBAN Mathis : 14h00<br />\nAVET Tanguy : 14h15<br />\nBOUYER Christopher : 14h30<br />\nCHAMBE Th&eacute;ophane : 14h45<br />\nCOULON DEPUCCIO Jordan : 14h00<br />\nDESRAYAUD Liam : 14h15<br />\nFERTILLE Eliott : 14h30<br />\nJORDA Marion : 14h45<br />\nMASSACRY Audran : 15h30<br />\nMOURIERAS Romain : 15h45<br />\nOLIVEIRA REIS Rodrigo : 16h00<br />\nREY Florian : 15h30<br />\nTROCCAZ Jeremy : 15h45<br />\nYANGUAS BEN BELA&Iuml;D Alexis : 16h00</p>',
  },
];

module.exports = response;
